version: '3.7'
services:
  db:
    image: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5434:5432'
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '8080:8080'